# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: stt.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'stt.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\tstt.proto\x12\x03stt\"\x0e\n\x0cStartRequest\" \n\rStartResponse\x12\x0f\n\x07message\x18\x01 \x01(\t\"\r\n\x0bStopRequest\"0\n\x0cStopResponse\x12\x0f\n\x07message\x18\x01 \x01(\t\x12\x0f\n\x07results\x18\x02 \x03(\t\"\x19\n\x17StreamRecognizedRequest\"(\n\x18StreamRecognizedResponse\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\t2\xbc\x01\n\nSTTService\x12.\n\x05Start\x12\x11.stt.StartRequest\x1a\x12.stt.StartResponse\x12+\n\x04Stop\x12\x10.stt.StopRequest\x1a\x11.stt.StopResponse\x12Q\n\x10StreamRecognized\x12\x1c.stt.StreamRecognizedRequest\x1a\x1d.stt.StreamRecognizedResponse0\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'stt_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_STARTREQUEST']._serialized_start=18
  _globals['_STARTREQUEST']._serialized_end=32
  _globals['_STARTRESPONSE']._serialized_start=34
  _globals['_STARTRESPONSE']._serialized_end=66
  _globals['_STOPREQUEST']._serialized_start=68
  _globals['_STOPREQUEST']._serialized_end=81
  _globals['_STOPRESPONSE']._serialized_start=83
  _globals['_STOPRESPONSE']._serialized_end=131
  _globals['_STREAMRECOGNIZEDREQUEST']._serialized_start=133
  _globals['_STREAMRECOGNIZEDREQUEST']._serialized_end=158
  _globals['_STREAMRECOGNIZEDRESPONSE']._serialized_start=160
  _globals['_STREAMRECOGNIZEDRESPONSE']._serialized_end=200
  _globals['_STTSERVICE']._serialized_start=203
  _globals['_STTSERVICE']._serialized_end=391
# @@protoc_insertion_point(module_scope)
